baseurl: https://marintarisa.github.io/ 
title: Marintarisa

paginate: 20
theme: PaperMod
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
minify:
  disableXML: true
  minifyOutput: true
params:
  env: production
  title: Marintarisa

  description: "inspiration for your reference to find light in darkness"
  keywords: [Blog, Portfolio, Images,  Download]
  author: Me
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto
  disableThemeToggle: false
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: true
  assets:
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"
  label:
    text: "Home"
    icon: /apple-touch-icon.png
    iconHeight: 35
  profileMode:
    enabled: false
    title: ExampleSite
    subtitle: "This is subtitle"
    imageUrl: "<img location>"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags
  homeInfoParams:
    Title: "Hi there 🤖 👋"
    Content: Welcome to my blog
  cover:
    hidden: true
    hiddenInList: true
    hiddenInSingle: true
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false    
markup:
  goldmark:
    renderer:
      unsafe: true
    
sitemap:
  filename: _.xml
